parameters:
    hoathis.ruler.class: Hoa\Ruler\Ruler

services:
    hoathis.ruler.raw:
        class:  %hoathis.ruler.class%
        public: false

    hoathis.ruler:
        alias: hoathis.ruler.raw
